### ISSUE TITLE
Schriftart wird in Windows 11 nicht erkannt

### ISSUE THREAD

**Issue by matheharry** [WienerSchriften/Primae#1]
Folgende Fehlermeldung erscheint, wenn eine der *.otf bzw. *.ttf Schriften installiert werden soll:

_Bei der Datei "D:\Eigene Dateien\...\Prima-Cursive.otf" scheint es sich nicht um eine gültige Schriftart zu handeln._

**Comment by WienerSchriften** [comment]
Danke für die Meldung, wir können das bisher nicht reproduzieren, schauen uns das aber genauer an.

**Comment by matheharry** [comment]
Jetzt geht's - allerdings nicht mit den hier gespeicherten Schriftarten, sondern nur mit der otf, heruntergeladen von der Homepage ...

**Comment by WienerSchriften** [comment]
Danke für die Nachricht, schön, dass sich das Problem erledigt hat!
