### ISSUE TITLE
Kursiv Buchstabenabstand

### ISSUE THREAD

**Issue by KiloJul** [WienerSchriften/Primae#2]
Ich habe Probleme bei der Kursiv - Schrift. Die Buchstabenabstände sind unregelmäßig. f und t überlagern sich. 

Gleiches Problem bei der MS - Word APP und Word 2016 auf Windows 10 Education und W10 Enterprise. Ich habe bei den Abstandseinstellungen in Word bei den Schriftarten herumprobiert - ohne Erfolg. 

Ich habe auf zwei getrennten PCs einmal mit dem otf und einmal mit dem ttf - Format probiert. 

<img width="470" alt="prima beispiel" src="https://user-images.githubusercontent.com/125873602/220872017-3bc0d706-aad5-4e84-a2fd-7536d1e96a9a.png">

**Comment by WienerSchriften** [comment]
In Microsoft Word ist das OpenType Feature 'Kontextuelle Varianten' leider nicht standardmäßig aktiviert. Es lässt sich aber einfach aktivieren indem im Menü 'Schriftart' im Reiter 'Erweitert' das entsprechende Kästchen 'Kontextvarianten verwenden' angehakt wird. Hier empfiehlt es sich auch im gleichen Schritt 'Unterschneidungen ab 1 pt' zu aktivieren. 
Siehe auch das erklärende Video hier: https://prima.wien/schreibschrift

**Comment by KiloJul** [comment]
Vielen Dank! Das hat funktioniert. 

Allerdings nur im docx - Format. Auch im Kompatitbilitätsmodus von Word klappt es nicht.

**Comment by WienerSchriften** [comment]
Ausgezeichnet, danke für die Rückmeldung.
