### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by haschka** [WienerSchriften/Primae#3]
Also wenn der Staat die Entwicklung einer Schrift mitfinanziert hätte man sich schon eine liberalere Lizenz die allen Bürgern zu gute kommt wie OFL-1.1 gewünscht.
Anstatt eine Lizenz die Kommerzielle, i.e. wenn ich die jetzt auf meinen Slides für ein Vorstellungspräch verwenden will - nicht erlaubt. Andere Staaten, i.e. Australien schaffen es ja auch, und die Font sieht ziemlich ähnlich aus. Man siehe, und möge doch eine ähnliche Lizenz wählen. 
https://github.com/MezMerrit/AU-School-Handwriting-Fonts
https://fonts.googleblog.com/2022/08/the-handwriting-fonts-that-help.html

Vielleicht kann man hier mit politischen Druck eine Änderung erbringen. Wenn die Stadt Wien mit Steuergeldern von allen zahlt, dann bitte auch eine Schrift für alle. Auch für den laden an der Ecke der die "Schulschrift" für seinen Katalog verwendet.

**Comment by haschka** [comment]
Frankreich zum Beispiel verwendet, hier:
https://eduscol.education.fr/204/polices-de-caracteres-cursives-pour-l-enseignement-de-l-ecriture
CC-BY-ND auch besser, als die Lizenz hier.

**Comment by WienerSchriften** [comment]
1.     Diese Plattform dient der gemeinschaftlichen Softwareentwicklung. Politische Diskussionen tragen nicht direkt dazu bei und passen nicht in die Kategorie 'issues' dieses Repositorys. Bitte diese Fragen in Zukunft in anderen Foren aufzubringen.
2.     Die Lizenz ist bereits sehr liberal, einzig die kommerzielle Verwertung ist mit dieser Lizenz untersagt. Jeder kann die Schrift für alles verwenden, und wenn er sie kommerzialisieren will, wird er um einen Beitrag gebeten. Außerdem ist das eine kuriose Logik: weil ein Verein der einem Bundesland nahe ist der Auftraggeber war, dürfen die Urheber das Produkt nicht kommerziell vertreiben, aber jeder andere darf damit Geld machen? Weiters sind die Beispiele, die Sie anführen unpassend: ein Vorstellungsgespräch als kommerzielle Nutzung zu deuten ist lächerlich, während die Erstellung von Lehrbüchern und anderen Unterlagen, die im Unterricht verwendet werden, ein großes, lukratives Geschäft ist.
3.     There is no free lunch on the web. Die australischen Schriften, die Sie anführen, wurden von Google umgesetzt. Dass Google seine Dienste unentgeltlich anbietet, basiert auf einem Geschäftsmodell, bei dem die Allgemeinheit anders als mit Geld bezahlt. Das für Philanthropie zu halten ist naiv. Das Gleiche trifft auch auf die Open Font License zu: Sie wurde von einer großen evangelikalen Organisation kreiert um ihre missionarischen Ziele voranzutreiben. In beiden Fällen klingt die 'freie' Software zunächst verlockend, doch es ist sinnvoll zu hinterfragen, woher das Geld für diese gratis Services kommt und was damit weiter unterstützt wird.
4.     Während der Wiener Bildungsserver das Projekt initiiert und mit einem einmaligen Honorar unterstützt hat, ist zu diesem Zeitpunkt keine weitere Finanzierung geplant. Schriften sind aber Software und müssen weiter entwickelt werden. Bei einer Veröffentlichung mit einer CC Lizenz und einer Veröffentlichung der Quellen bedeutet das außerdem die weitere Betreuung der Daten. Der Kunde hätte dafür weder die Mittel noch die Kompetenz, aus diesem Grund sind wir zu der Übereinkunft gekommen, dass wir diese Arbeit übernehmen und die Qualitätssicherung für die weitere Entwicklung bereitstellen. Dafür behalten wir das Recht ein kommerzielle Lizenzen zur Verwendung des Produktes zu vertreiben. In diesem Sinne ist auch meine Antwort an Sie ein Teil dieser Übereinkunft: etwaige zukünftige Lizenznehmer bezahlen (hoffentlich) die Zeit, die ich gerade für Sie aufgewandt habe.
5.     Die Lizenz der französischen Schrift ist viel restriktiver: sie erlaubt keinerlei Modifikation oder darauf basierende Derivate. Außerdem ist im französischen Modell keine weitere Betreuung und Entwicklung der Schrift geplant – ein konzeptioneller Kardinalfehler: etwas einfach nur gratis in die Welt zu werfen ohne sich über die weitere Entwicklung Gedanken zu machen ist nicht durchdacht.

**Comment by haschka** [comment]
@WienerSchriften 
Ich verstehe Ihr Argument natürlich, dass Sie nur einmal bezahlt worden sind. 

Aber Ich kann mir bei allen Guten willen nicht vorstellen, dass es im Sinne der Stadt Wien oder seiner Bevölkerung sei, dass die Schrift die man in der Schule erlernt nicht "frei", kommerziell oder nicht, verfügbar ist. 

Ich persönlich werde auch vom Französischen Staat für meine wissenschaftliche Arbeit bezahlt, und meine Software und Publikationen sind daher auch für die gesamte Bevölkerung und darüber hinausgehend verwendbar. Das trägt auch zum Wirtschaftstandort bei, da natürlich auch Industrien/etc. dieses öffentliche Wissen "frei" für Ihre (auch kommerzielle) Zwecke verwenden können. Aus diesem Grund gibt es freie Softwarelizenzen oder die FSF etc. 

Es ist eben leider in Ihrer Lizenz nicht klar, und Sie gibt Ihnen das Recht auch wenn Ihnen das Beispiel: "Slides für eine Bewerbung" als lapidar dargestellt kling, dafür Geld zu verlangen. 

Es ist natürlich eine Lizenz die eine freie Nutzung erlaubt besser, auch wenn Sie keine Garantien gibt. Zu diesem Argument, Sie geben hier zwar eine Weiterentwicklung an, aber dazu auch keine Garantien ab! Es ist für mich einfach nicht vorstellbar, dass jene Schrift die an der Schule gelehrt wird, später für kommerzielle oder welcher Zwecke auch immer Lizenzgebüren anfallen sollen. 

Ohne hier eine Schuld zu zuweisen. Es ist von der Stadt Wien einfach die falsche Vorgehensweise hier im Auftrag nicht klar festzulegen, dass diese Schrift frei für alle sein soll.

**Comment by trapicki** [comment]
Es bleibt aus dem Absatz "Lizenz" in der README.md unklar, was eine nich-kommerzielle Nutzung einer Schrift umfasst.

Ist bei einer Schrift das so zu verstehen wie z.B. mit dem Linux-Kernel, also dass das Werk selber frei benutzbar/studierbar/anpassbar/verbreitbar ist, aber sich die Lizenz nicht auf die damit verwendeten Programme erstreckt? Das würde bedeuten, dass jedes mit dem Font erstellte Dokument nicht von der Lizenz  betroffen ist. Für eingebettete Fonts wie z.B. bei PDF stellt sich die Frage ob die Lizenzbedingungen angeführt werden müssen, weil ja eine Weiterverbreitung  statt finded.

Oder sind Werke, die mit dem Font erstellt wurden automatisch von der Lizenz umfasst, und für jedes Werk, das mit dem Font erstellt wurde und das kommerziell verbreitet wird (also für das als Werk Geld verlangt wird) wäre eine gesonderte kommerzielle Lizenz notwendig? Braucht es eine Lizenz, wenn man ein Schreiblernbuch für Prima erstellt?

Ich hätte verstanden, dass die Lizenz selber nur den Font betrifft, dieser als frei weiterverteilt werden kann, unter Beibehaltung der Lizenz (SA share alike), Nennung der UrheberInnen (BY), auch mit Veränderungen, aber nicht gegen Geld für den Font oder davon abgeleitete Fonts (NC non-commercial).

**Comment by skurzinz** [comment]
@trapicki Dazu sollte die verlinkte https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de eigentlich als Information ausreichen.

Ich würde davon ausgehen, dass die Verwendung der Schrift in einem Druckwerk schon eine Verwendung ist, die der Lizenz unterliegt. 

Definition von NC: https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses 

## Beispiele für legitime Nutzung nach der hier vergebenen Lizenz 

(die ja ein weiteres Licensing nicht ausschließt, es könnte also jemand mit den Urhebern vermutl. gegen Vergütung oder weil sie nett gefragt hat, die Erlaubnis erhalten, die Schrift auch kommerziell zu verwenden)

Das von @trapicki angedachte Schreiblernbuch 

- beinhaltet einen Hinweis auf die Schrift, ihre AutorInnen und die Lizenz
- wird verschenkt oder nur herstellungskostendeckend verkauft

Die Prima wird (nach dem Beispiel von @haschka) erweitert um weitere Schnitte, dabei kommen weitere UrheberInnen dazu und
- diese bleiben bei der BY-NC-SA
- nennen die Ersturheber
- die weiteren UrheberInnen "verdienen nichts daran" oder haben kein primär kommerzielles Interesse daran

## Beispiele für nichtlegitime Nutzung nach der hier vergebenen Lizenz

Das Schreiblernbuch

- wird gewinnbringend verkauft und/oder
- nennt Prima, Urheber oder Lizenz nicht

Die Erweiterung der Prima wird gewinnbringend verkauft und/oder es wird keine oder eine andere Lizenz vergeben und/oder es wird nicht auf die geistige Schöpfung der Urheber hingewiesen. 

Ob das Schreiblernbuch als ganzes ebenfalls BY-NC-SA-lizensiert sein muss? Es ließe sich argumentieren, dass es, nachdem es ein Schreiblernbuch ist und die Prima eine Schreiblernschrit, als ganzes der geistigen Schöpfung der Urheber der Prima unterliegen müsste -- dann wäre diese Lizenzierung notwendig. Wenn derselbe Inhalt alleine und ohne die Schrift Schöpfungshöhe erreichen würde, dann könnte Nennung nach BY ausreichen^[1]. Aber im Zweifelsfall kann man ja einfach fragen bei @WienerSchriften bzw. @idiidiiidesign: Die Lizenz ist ja nur ein Versprechen, urheberrechtlich nicht gegen Nutzungen nach deren Bedingungen vorzugehen. 

[1] Das ist heikel und vermutl. der Grund, warum für gänzlich freie Fonts eher die [OFL](https://openfontlicense.org/) vergeben wird als eine CC-Lizenz.
