### ISSUE TITLE
Adobe Software Behavior

### ISSUE THREAD

**Issue by rosaiani** [WienerSchriften/Primae#4]
Latest Adobe Illustrator/Indesign don't recognize the ot features that make the font work.
It's working on Text Edit/Word both mac and pc.
Any thoughts on why is that?

**Comment by WienerSchriften** [comment]
Which paragraph composer are you using? I guess you may not be using the so-called 'Adobe World-Ready Paragraph Composer'? Please verify and report back here.

**Comment by rosaiani** [comment]
Great, it works. Maybe adding that to the readme/installation instructions might save people some hassle. Thanks for the quick answer!

**Comment by rosaiani** [comment]
Also, in Illustrator settings > Type > Show Indic options
<img width="845" alt="image" src="https://github.com/WienerSchriften/Prima/assets/237202/813ec02a-99e8-4c6b-b770-bb54b1d62dac">
<img width="892" alt="image" src="https://github.com/WienerSchriften/Prima/assets/237202/5e463d52-5b8e-4244-9d46-207aa7c67775">
and then in paragraph > extra options > Middle Easter/Asian paragraph composer
<img width="892" alt="image" src="https://github.com/WienerSchriften/Prima/assets/237202/3db06d01-30ec-405d-8b9a-689dc1ecb448">


these are important settings for the font to work in Adobe Software.

**Comment by WienerSchriften** [comment]
Hi, I am glad that could be resolved quickly and easily. You are absolutely right about the readme, I will see to it.
